#ifndef INCLUDED_DS_H
#define INCLUDED_DS_H

#define KEY_BIT_SIZE 512

#define NO_OF_CHARACTERS 93

#define INITIAL_EXPONENT_FOR_RSA 65537

#define STRONG_PRIME_BIT_SIZE 512
#define NO_OF_REPS_FOR_PROBABILISTIC_PRIMALITY_TEST 200

#endif